# RustDesk конфигурация — генерирана автоматично
# Сървъри на Драже - support.drazhev.net

[options]
custom-rendezvous-server = "hjc0a1kp4be.vpn.mynetname.net"
relay-server = "hjc0a1kp4be.vpn.mynetname.net"
api-server = "http://hjc0a1kp4be.vpn.mynetname.net:21114"
key = "PyMhoZr13G9aPMgshwW7XHzV86jU+MIssK80Nh9GYzc="
