# RustDesk конфигурация — генерирана автоматично
# Сървъри на Драже - support.drazhev.net

[options]
custom-rendezvous-server = "192.168.222.21"
relay-server = "192.168.222.21"
api-server = "http://192.168.222.21:21114"
key = "PyMhoZr13G9aPMgshwW7XHzV86jU+MIssK80Nh9GYzc="
